// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vpassbackend.Data;

#nullable disable

namespace Vpassbackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250710000001_AddCoordinatesToServiceCenter")]
    partial class AddCoordinatesToServiceCenter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // The rest of the model would normally be here but we're only focusing on the changes
#pragma warning restore 612, 618
        }
    }
}
