// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vpassbackend.Data;

#nullable disable

namespace Vpassbackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250710190000_AddServiceReminders")]
    partial class AddServiceReminders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Model content not included for brevity
            // The DbContext will automatically populate this when migrations are run
#pragma warning restore 612, 618
        }
    }
}
